[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "cmake"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python run_production.py"
